### ISSUE TITLE
Access denied to supposedly public S3 bucket

### ISSUE THREAD

**Issue by mribeirodantas** [nf-core/references#11]
I tried to list the files in the S3 bucket with the AWS CLI and no credentials (`--no-sign-request`) but got access denied.

## Steps to reproduce

```console
aws s3 ls s3://nf-core-references-scratch/test-results/953cbe91-f2e1-489d-aac2-ed696e26da9f/R64-1-1/star/ --no-sign-request
```

## Error output

```console
An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```

**Comment by edmundmiller** [comment]
That's the scratch directory 😆 Whoops.

Try 
```bash
aws s3 ls s3://nf-core-references
```

**Comment by mribeirodantas** [comment]
![CleanShot 2024-02-08 at 15 45 31@2x](https://github.com/nf-core/references/assets/1023197/eadcb96e-f23b-446f-8594-92c533171e00)

Yay! 🥳
